spring:
  application:
    name: First-project

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: MongoQueries

  mail:
    host: smtp.gmail.com
    port: 587
    username: kira3092650@gmail.com
    password: aqngcvjpnusuyrwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    queue:
      name: myQueue
    exchange:
      name: myExchange
    routing-key: myRoutingKey

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


